default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: football_stat_development

test:
  <<: *default
  database: football_stat_test

production:
  <<: *default
  database: football_stat_production
  username: football_stat
  password: <%= ENV['FOOTBALL_STAT_DATABASE_PASSWORD'] %>
